#pragma once

// RGB data line and six SK6812MINI-E LEDs.
#define WS2812_DI_PIN GP0
#define RGBLIGHT_LED_COUNT 6
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define RGBLIGHT_LAYERS

// Compile RGBLight animation modes into the firmware.
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
